#!/usr/bin/bash

TARGETDIR=$1
echo $TARGETDIR
rm -rf $TARGETDIR
mkdir $TARGETDIR
cd $TARGETDIR

if [ $TARGETDIR == 'stage1_linux' ]; then
	cmake -GNinja ../llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_OPTIMIZED_TABLEGEN=ON -DCMAKE_C_COMPILER=clang-15 -DCMAKE_CXX_COMPILER=clang++-15 -DCMAKE_LINKER=ld.lld-15 -DLLVM_ENABLE_LLD=ON -DLLVM_ENABLE_PROJECTS="llvm;lld" -DBUILD_SHARED_LIBS=ON
fi
